import type { Role } from "@prisma/client";

// Role × capability map (T1.3) — the spec §3 access matrix as a code table.
// Frontend filtering is never enforcement; this table is.

export const CAPABILITIES = [
  "workspace.manage",
  "members.manage",
  "clients.read",
  "clients.write",
  "contacts.read",
  "contacts.write",
  "properties.read",
  "properties.write",
  "listings.read",
  "listings.write",
  "listings.publish",
  "offers.read",
  "offers.write",
  "offers.decide",
  "offers.respond",
  "contracts.read",
  "contracts.write",
  "movein.read",
  "movein.write",
  "movein.acknowledge",
  "landlords.verify",
  "tenancies.read",
  "tenancies.write",
  "tenancies.upload",
  "payments.read",
  "payments.write",
  "deadlines.read",
  "deadlines.write",
  "renewals.read",
  "renewals.write",
  "renewals.decide",
  "documents.read",
  "documents.write",
  "imports.manage",
  "proofs.read",
  "proofs.write",
  "proofs.decide",
  "passport.read",
  "passport.write",
  "passport.share",
  "enquiries.read",
  "enquiries.write",
  "viewings.read",
  "viewings.write",
  "evidence.read",
  "riskflags.read",
  "riskflags.ack",
  "reports.generate",
  "reports.read",
  "notifications.read",
  "messaging.manage",
] as const;

export type Capability = (typeof CAPABILITIES)[number];

const ALL = [...CAPABILITIES] as Capability[];

const READ_PORTFOLIO: Capability[] = [
  "clients.read",
  "contacts.read",
  "properties.read",
  "tenancies.read",
  "payments.read",
  "deadlines.read",
  "renewals.read",
  "documents.read",
  "proofs.read",
  "evidence.read",
  "riskflags.read",
  "reports.read",
];

export const ROLE_CAPABILITIES: Record<Role, Capability[]> = {
  WORKSPACE_ADMIN: ALL,
  FIDUCIARY: ALL.filter((c) => c !== "workspace.manage" && c !== "members.manage"),
  MANAGER: [
    ...READ_PORTFOLIO,
    "clients.write",
    "contacts.write",
    "properties.write",
    "listings.read",
    "listings.write",
    "listings.publish",
    "offers.read",
    "offers.write",
    "offers.decide",
    "contracts.read",
    "contracts.write",
    "movein.read",
    "movein.write",
    "movein.acknowledge",
    "landlords.verify",
    "tenancies.write",
    "payments.write",
    "deadlines.write",
    "renewals.write",
    "renewals.decide",
    "documents.write",
    "imports.manage",
    "proofs.write",
    "proofs.decide",
    "passport.read",
    "enquiries.read",
    "enquiries.write",
    "viewings.read",
    "viewings.write",
    "riskflags.ack",
    "reports.generate",
    "notifications.read",
    "messaging.manage",
  ],
  // CLIENT_VIEWER is additionally scoped to a single ClientPrincipal in authz.
  CLIENT_VIEWER: READ_PORTFOLIO,
  AGENT: [
    "contacts.read",
    "properties.read",
    "tenancies.read",
    "deadlines.read",
    "renewals.read",
    "proofs.read",
    "documents.read",
  ],
  // Execution delegate (F0d): read + broad WRITE, but every path is confined to
  // Membership.assignedClientIds (AuthzContext.delegateClientIds) — see
  // services/delegateScope.ts. It does NOT hold the fiduciary-control caps
  // (proofs.decide), the roster (clients.*), members/workspace admin,
  // renewals.decide, landlords.verify, or cross-client reports.* — those are simply
  // not granted here. listings.*/offers.*/contracts.* arrive with their surfaces.
  MANAGING_AGENT: [
    "contacts.read",
    "properties.read",
    "properties.write",
    "tenancies.read",
    "tenancies.write",
    "tenancies.upload",
    "payments.read",
    "payments.write",
    "deadlines.read",
    "deadlines.write",
    "renewals.read",
    "documents.read",
    "documents.write",
    "proofs.read",
    "proofs.write",
  ],
  LICENSED_PARTNER: [
    "properties.read",
    "tenancies.read",
    "deadlines.read",
    "renewals.read",
    "proofs.read",
    "proofs.write",
    "documents.read",
    "documents.write",
  ],
  VENDOR: ["proofs.read", "documents.write"],
  AUDITOR: [...READ_PORTFOLIO, "notifications.read"],
  // Self-service personas, each additionally scoped to ONE Contact in authz via
  // Membership.subjectContactId (see services/contactScope.ts). F0a grants only
  // the read capabilities whose service paths are contact-scoped and tested here;
  // offers.* / renewals.* arrive with their authenticated services in Stage 2.
  TENANT: [
    "tenancies.read",
    "tenancies.upload",
    "payments.read",
    "deadlines.read",
    "documents.read",
    "proofs.read",
    "offers.read",
    "offers.respond",
    "passport.read",
    "passport.write",
    "passport.share",
    "movein.read",
    "movein.acknowledge",
  ],
  LANDLORD: [
    "properties.read",
    "listings.read",
    "listings.write",
    "listings.publish",
    "offers.read",
    "offers.write",
    "offers.decide",
    "contracts.read",
    "contracts.write",
    "movein.read",
    "movein.acknowledge",
    "tenancies.read",
    "payments.read",
    "deadlines.read",
    "documents.read",
    "proofs.read",
  ],
};

export function roleHas(role: Role, capability: Capability): boolean {
  return ROLE_CAPABILITIES[role].includes(capability);
}
